---
title: 'MATH 324 Final Project'
author: "Group Members Names Here"
output:
  pdf_document: default
  html_notebook: default
---

  
```{r, include = F, warning=F, message=F}
# front-matter
rm(list = ls()) #clear the workspace

library(Stat2Data)
library(tidyverse)
library(mosaic)
library(ggformula)
library(emmeans)


knitr::opts_chunk$set(echo = F)
```

# 1. Project Description

*Should be in paragraph form (not bullets).  Written for a 3rd party client that may not have a strong statistical background. As part of your description, consider the following:*

- *Description of the dataset*
- *Goal of study*

## 1.1 Research Objectives


*What are the overarching research objectives that the study is targeting? (not just a restatement of the original research objectives)*

**Objective 1:**  

**Objective 2:**

**Objective 3:**


## 1.2 Variables

*What is (are) possible explanatory and response variables?*

*Create a table here - it should include variable names and types*

#  2. Detailed Exploratory Data Analysis (EDA)

*Spend time investigating the data thoroughly and use this section to present figures that allow you to visualize the relationship of the response to different predictors.  Include descriptions of the figures that illustrate what you can learn from them.*


# 3. Statistical Analysis 

*Describe the statistical analysis that you used to answer Research Objectives 1-3. Each analysis should be labeled for the appropriate research objective. This section should summarize all relevant analyses that lead to your final conclusions/decisions/recommendations. Be sure to include:*

- *Model Assumptions & how checked/verified*
- *Interpretation of relevant estimates/statistics/p-values IN CONTEXT*
- *Any data manipulation to create new variables* 

*You should not include your code. However, I would like to see the code for final models that you are using to answer the research objectives in the appendix.* 

## 3.1 Objective 1

## 3.2 Objective 2

## 3.3 Objective 3

# 4. Conclusions 

*Succinct response to each question laid out in 1.1.  This a much shorter version of section 3, and focuses on conclusions rather than the analyses.*

**Objective 1:**  

**Objective 2:**

**Objective 3:**

*(all research objectives should be addressed, in the same order)*

# 5. Appendix 

*This section should include the code and output for the models used to answer the research objectives.*
